# Model Configuration
model:
  name: "genomic_variant_classifier"
  version: "1.0.0"
  
  # Model parameters
  random_state: 42
  test_size: 0.2
  validation_size: 0.1
  
  # XGBoost parameters
  xgboost:
    n_estimators: 1000
    max_depth: 10
    learning_rate: 0.01
    objective: "binary:logistic"
    n_jobs: -1
    early_stopping_rounds: 50
    
  # LightGBM parameters
  lightgbm:
    num_leaves: 31
    learning_rate: 0.05
    feature_fraction: 0.9
    bagging_fraction: 0.8
    bagging_freq: 5
    verbose: 0
    
  # Neural Network parameters
  neural_network:
    hidden_layers: [512, 256, 128]
    dropout_rate: 0.3
    batch_size: 32
    epochs: 100
    learning_rate: 0.001
    optimizer: "adam"

# Data Configuration
data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  external_data_path: "data/external"
  interim_data_path: "data/interim"
  
  # VCF processing
  vcf:
    quality_threshold: 30
    depth_threshold: 10
    allele_frequency_threshold: 0.01
    
  # Feature engineering
  features:
    sequence_context_size: 10
    conservation_scores: ["phyloP", "phastCons", "GERP"]
    functional_annotations: ["SIFT", "PolyPhen2", "CADD", "REVEL"]
    
# Training Configuration
training:
  batch_size: 64
  num_workers: 4
  pin_memory: true
  
  # Cross-validation
  cv_folds: 5
  stratified: true
  
  # Early stopping
  patience: 10
  min_delta: 0.001
  
# MLflow Configuration
mlflow:
  tracking_uri: "mlruns"
  experiment_name: "genomic_variant_analysis"
  artifact_location: "models/artifacts"
  
# DVC Configuration
dvc:
  remote: "s3"
  cache_dir: ".dvc/cache"
  
# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 4
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/genomic_analysis.log"