# Gene Variant Analysis Configuration

# Data paths
data:
  raw: "data/raw"
  processed: "data/processed"
  external: "data/external"
  interim: "data/interim"
  features:
    sequence_context_size: 50

# Model configuration
model:
  test_size: 0.2
  validation_size: 0.1
  random_state: 42
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
  lightgbm:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    num_leaves: 31
    feature_fraction: 0.8
    bagging_fraction: 0.8
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
  gradient_boosting:
    n_estimators: 100
    max_depth: 5
    learning_rate: 0.1
  logistic_regression:
    max_iter: 1000
    C: 1.0

# Feature engineering
features:
  variant_features:
    - "chromosome"
    - "position"
    - "ref_allele"
    - "alt_allele"
    - "variant_type"
  sequence_features:
    - "gc_content"
    - "repeat_content"
    - "conservation_score"
  annotation_features:
    - "gene_name"
    - "transcript_id"
    - "consequence"
    - "impact"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/gene_variant_analysis.log"

# MLflow configuration
mlflow:
  tracking_uri: "file:./mlruns"
  experiment_name: "gene_variant_analysis"

# DVC configuration
dvc:
  remote: "local"
  cache_dir: ".dvc/cache"